# Production profile
server:
  port: 9001
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        secure: true   # HTTPS only cookie
spring:
  thymeleaf:
    cache: true
app:
  allowed-origins: "https://tda.mr486.com"
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
